# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bitrise < Formula
  desc "Command-line tool for Bitrise CI/CD"
  homepage "https://github.com/sp3esu/bitrise-cli"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sp3esu/bitrise-cli/releases/download/v1.0.1/bitrise_darwin_amd64.tar.gz"
      sha256 "fa95ceb867bb81820318c6a9e4517f5487194aa73a8650b2018e46e3d1ec9c59"

      define_method(:install) do
        bin.install "bitrise"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sp3esu/bitrise-cli/releases/download/v1.0.1/bitrise_darwin_arm64.tar.gz"
      sha256 "091a7489181d0cc18e92a600e9d28529add5514bcc6acf08b63595cc7f1facc0"

      define_method(:install) do
        bin.install "bitrise"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sp3esu/bitrise-cli/releases/download/v1.0.1/bitrise_linux_amd64.tar.gz"
      sha256 "59312a6957b20805de8ec30ee3251d1fd25d9cd74a43663682ee874b233ec1cd"
      define_method(:install) do
        bin.install "bitrise"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sp3esu/bitrise-cli/releases/download/v1.0.1/bitrise_linux_arm64.tar.gz"
      sha256 "04589574647589530720feea7bcdef68d705f76b50fb5edd39c1c6afc38e7751"
      define_method(:install) do
        bin.install "bitrise"
      end
    end
  end

  test do
    assert_match(/bitrise/, shell_output("#{bin}/bitrise version"))
  end
end
