# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bitrise < Formula
  desc "Command-line tool for Bitrise CI/CD"
  homepage "https://github.com/sp3esu/bitrise-cli"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sp3esu/bitrise-cli/releases/download/v1.0.0/bitrise_darwin_amd64.tar.gz"
      sha256 "f9227c97338e8f47342c612ccdd1f11178f3c710342855943b084b6aed508f72"

      define_method(:install) do
        bin.install "bitrise"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sp3esu/bitrise-cli/releases/download/v1.0.0/bitrise_darwin_arm64.tar.gz"
      sha256 "645680edc90c9f2e4c3fc03f82045f226ffd7ef142e07816580d1768c6ccb971"

      define_method(:install) do
        bin.install "bitrise"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sp3esu/bitrise-cli/releases/download/v1.0.0/bitrise_linux_amd64.tar.gz"
      sha256 "102e07d3d76257ca28703fdccdfa19b00ed28d516f970b4ac3ca3bd40fee20e1"
      define_method(:install) do
        bin.install "bitrise"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sp3esu/bitrise-cli/releases/download/v1.0.0/bitrise_linux_arm64.tar.gz"
      sha256 "130c0cee2e0bc608191a0c5ab3072b7904ea7fc481c183ca4387a7d0567b9a8a"
      define_method(:install) do
        bin.install "bitrise"
      end
    end
  end

  test do
    assert_match(/bitrise/, shell_output("#{bin}/bitrise version"))
  end
end
