# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MacCleaner < Formula
  desc "Fast, safe CLI tool for macOS to scan and reclaim disk space"
  homepage "https://github.com/sp3esu/mac-cleaner"
  version "1.7.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/sp3esu/mac-cleaner/releases/download/v1.7.1/mac-cleaner_darwin_amd64.tar.gz"
    sha256 "87345f1066877d37dcd5efd0095839d96be093adef78de68b276da135e2f1f06"

    define_method(:install) do
      bin.install "mac-cleaner"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/sp3esu/mac-cleaner/releases/download/v1.7.1/mac-cleaner_darwin_arm64.tar.gz"
    sha256 "305f3f3c2fcda0a19d140b5b8e94dc1e426366acc9113ae2054ee6d9022afd18"

    define_method(:install) do
      bin.install "mac-cleaner"
    end
  end

  test do
    system "#{bin}/mac-cleaner", "--version"
  end
end
